# Generated by Django 4.1.7 on 2023-03-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjuster',
            options={'verbose_name': 'Adjuster', 'verbose_name_plural': 'Adjusters'},
        ),
        migrations.AlterModelOptions(
            name='autoshop',
            options={'verbose_name': 'Auto shop', 'verbose_name_plural': 'Auto shops'},
        ),
        migrations.AlterModelOptions(
            name='claim',
            options={'verbose_name': 'Claim', 'verbose_name_plural': 'Claims'},
        ),
        migrations.AlterModelOptions(
            name='damage',
            options={'verbose_name': 'Damage', 'verbose_name_plural': 'Damages'},
        ),
        migrations.AlterModelOptions(
            name='damagephoto',
            options={'verbose_name': 'Damage photo', 'verbose_name_plural': 'Damage photos'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Guest', 'verbose_name_plural': 'Guests'},
        ),
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'verbose_name': 'Insurance company', 'verbose_name_plural': 'Insurance companies'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AddField(
            model_name='claim',
            name='observation',
            field=models.TextField(blank=True, help_text='Observations and notes about the claim', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='rental_agreement',
            field=models.FileField(null=True, upload_to='RentalAgreements/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='demand_file',
            field=models.FileField(blank=True, upload_to='DemandLetters/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='estimate_file',
            field=models.FileField(blank=True, upload_to='Estimates/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Open recently', 'Open'), ('Waiting on estimate', 'Waiting Estimate'), ('Estimate ready', 'Estimate Ready'), ('Estimate sent to insurance company', 'Estimate Sent'), ('Denied', 'Denied'), ('Demand letter sent', 'Demand Sent'), ('Waiting on payment from insurance company/Guest', 'Waiting Payment'), ('Paid', 'Paid'), ('Needs Deductible', 'Deductible'), ('Closed', 'Closed')], max_length=200),
        ),
    ]
